version: "3.7"

volumes:
  postgres-data:
  redis-cache:

networks:
  project001:
    name: project001
  project001-cache:
    name: project001-cache

services:
  graphql:
    build:
      context: .
      dockerfile: ./microservices/graphql/Dockerfile
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    networks:
      - project001
    ports:
      - 5432:5432

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  adminer:
    image: adminer
    restart: always
    networks:
      - project001
    ports:
      - 8088:8080

  redis:
    image: redis:7.0.11-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    # command: redis-server --save 20 1 --loglevel warning
    command: redis-server
    volumes: 
      - redis-cache:/var/lib/redis/data
    networks:
      - project001-cache

  rediscommander:
    image: rediscommander/redis-commander:latest
    restart: always
    networks:
      - project001-cache
    ports:
      - 8081:8081
