version: '3.8'

volumes:
  postgres-data:
  redis-cache:

networks:
  project001:
    name: project001
  project001-cache:
    name: project001-cache

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    networks:
      - project001
      - project001-cache

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    networks:
      - project001
    ports:
      - 5432:5432

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  adminer:
    image: adminer
    restart: always
    networks:
      - project001
    ports:
      - 8088:8080

  redis:
    image: redis:7.0.11-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    # command: redis-server --save 20 1 --loglevel warning
    command: redis-server
    volumes: 
      - redis-cache:/var/lib/redis/data
    networks:
      - project001-cache

  rediscommander:
    image: rediscommander/redis-commander:latest
    restart: always
    networks:
      - project001-cache
    ports:
      - 8081:8081

